### ISSUE TITLE
update read.me

### ISSUE THREAD

**Issue by thecodingwhale** [pinoyyid/ngManila-jan15#2]
I followed the instructions correctly and try running grunt serve. But then, I got plenty of errors. Is it OK if you update the READ.MD for beginners?

**Comment by thecodingwhale** [comment]
Here are my errors after running grunt serve:

``` sh
 sI: about to establish extension connection for WIDGET_CONTENT_MESSAGE - url: http://localhost:9000/
scriptInjector.js:191 sI: adding WIDGET_CONTENT_MESSAGE message listener
reservespaceifenabled.js:66 rsie: leaving js
angular.js:4117 Uncaught Error: [$injector:modulerr] Failed to instantiate module ngtodoApp due to:
Error: [$injector:modulerr] Failed to instantiate module LocalStorageModule due to:
Error: [$injector:nomod] Module 'LocalStorageModule' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.11/$injector/nomod?p0=LocalStorageModule
    at http://localhost:9000/bower_components/angular/angular.js:63:12
    at http://localhost:9000/bower_components/angular/angular.js:1764:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:1688:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:1762:14)
    at http://localhost:9000/bower_components/angular/angular.js:4094:22
    at forEach (http://localhost:9000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4078:5)
    at http://localhost:9000/bower_components/angular/angular.js:4095:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4078:5)
http://errors.angularjs.org/1.3.11/$injector/modulerr?p0=LocalStorageModule…2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4078%3A5)
    at http://localhost:9000/bower_components/angular/angular.js:63:12
    at http://localhost:9000/bower_components/angular/angular.js:4117:15
    at forEach (http://localhost:9000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4078:5)
    at http://localhost:9000/bower_components/angular/angular.js:4095:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4078:5)
    at createInjector (http://localhost:9000/bower_components/angular/angular.js:4004:11)
    at doBootstrap (http://localhost:9000/bower_components/angular/angular.js:1446:20)
    at bootstrap (http://localhost:9000/bower_components/angular/angular.js:1467:12)
http://errors.angularjs.org/1.3.11/$injector/modulerr?p0=ngtodoApp&p1=Error…F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1467%3A12)
contentScript.js:42 cS: logger: Array[1] : undefined
contentScript.js:42 cS: logger: Array[1] : undefined
contentScript.js:42 cS: logger: Array[1] : document ready
contentScript.js:42 cS: logger: Array[1] : running callback
contentScript.js:42 cS: logger: Array[1] : undefined
reservespaceifenabled.js:5 rsie: reserveSpace
reservespaceifenabled.js:7 rsie: getToolbarData
contentScript.js:42 cS: logger: Array[1] : undefined
contentScript.js:93 Uncaught ReferenceError: handleVisibilityChange is not defined
reservespaceifenabled.js:15 rsie: getToolbarDataCallback(Arguments[1])
reservespaceifenabled.js:25 rsie: window.toolbarData: Object
reservespaceifenabled.js:26 rsie: window.Content: Object
contentScript.js:42 cS: logger: Array[1] : undefined
contentScript.js:42 cS: logger: Array[1] : undefined
contentScript.js:42 cS: logger: Array[1] : document ready
contentScript.js:42 cS: logger: Array[1] : running callback
contentScript.js:42 cS: logger: Array[1] : undefined
contentScript.js:42 cS: logger: Array[1] : firing tab complete
contentScript.js:80 cS: sending TAB_COMPLETE
reservespaceifenabled.js:35 rsie: getToolbarDataCallback - done
contentScript.js:234 cs: onRequestListener(Arguments[3])
contentScript.js:234 cs: onRequestListener(Arguments[3])
```

**Comment by pinoyyid** [comment]
Hi Aldren

I've pushed a fix to github. My apologies. The issue was that the repo held
the .min.js version of the localstorage module, but the index.html was
trying to load the .js

best
Roy

**Comment by pinoyyid** [comment]
I will also update the readme when I get time

**Comment by thecodingwhale** [comment]
thank you, I'm looking forward for this coming Wednesday.

**Comment by DmitryOlkhovoi** [comment]
@pinoyyid sorry for offtop, what is it - sI: about to establish extension connection for WIDGET_CONTENT_MESSAGE? 
https://github.com/search?q=WIDGET_CONTENT_MESSAGE+message+listener&type=Code&utf8=%E2%9C%93

**Comment by DmitryOlkhovoi** [comment]
where is it using?
https://github.com/chrome-exts/fkfcmeoepjhclglafbppmeidjjolcgid/blob/839cabbffaaf2d33cdef5b20e2acc433cca963bd/js/scriptInjector.js?
